// Code generated by cmd/generate; DO NOT EDIT.

package bunq

type Amount struct {
	Value string `json:"value,omitempty"`
	Currency string `json:"currency,omitempty"`
}

type InvoiceItemGroup struct {
	Type string `json:"type,omitempty"`
	TypeDescription string `json:"type_description,omitempty"`
	TypeDescriptionTranslated string `json:"type_description_translated,omitempty"`
	InstanceDescription string `json:"instance_description,omitempty"`
	ProductVATExclusive *Amount `json:"product_vat_exclusive,omitempty"`
	ProductVATInclusive *Amount `json:"product_vat_inclusive,omitempty"`
	Item []*InvoiceItem `json:"item,omitempty"`
}

type InvoiceItem struct {
	ID int `json:"id,omitempty"`
	BillingDate string `json:"billing_date,omitempty"`
	TypeDescription string `json:"type_description,omitempty"`
	TypeDescriptionTranslated string `json:"type_description_translated,omitempty"`
	UnitVATExclusive *Amount `json:"unit_vat_exclusive,omitempty"`
	UnitVATInclusive *Amount `json:"unit_vat_inclusive,omitempty"`
	VAT float64 `json:"vat,omitempty"`
	Quantity float64 `json:"quantity,omitempty"`
	TotalVATExclusive *Amount `json:"total_vat_exclusive,omitempty"`
	TotalVATInclusive *Amount `json:"total_vat_inclusive,omitempty"`
}

type LabelMonetaryAccount struct {
	IBAN string `json:"iban,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	Avatar *Avatar `json:"avatar,omitempty"`
	LabelUser *LabelUser `json:"label_user,omitempty"`
	Country string `json:"country,omitempty"`
	BunqMe *MonetaryAccountReference `json:"bunq_me,omitempty"`
	IsLight bool `json:"is_light,omitempty"`
	SwiftBic string `json:"swift_bic,omitempty"`
	SwiftAccountNumber string `json:"swift_account_number,omitempty"`
	TransferwiseAccountNumber string `json:"transferwise_account_number,omitempty"`
	TransferwiseBankCode string `json:"transferwise_bank_code,omitempty"`
	MerchantCategoryCode string `json:"merchant_category_code,omitempty"`
}

type Image struct {
	AttachmentPublicUUID string `json:"attachment_public_uuid,omitempty"`
	ContentType string `json:"content_type,omitempty"`
	Height int `json:"height,omitempty"`
	Width int `json:"width,omitempty"`
}

type LabelUser struct {
	UUID string `json:"uuid,omitempty"`
	Avatar *Avatar `json:"avatar,omitempty"`
	PublicNickName string `json:"public_nick_name,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	Country string `json:"country,omitempty"`
}

type Pointer struct {
	Type string `json:"type,omitempty"`
	Value string `json:"value,omitempty"`
	Name string `json:"name,omitempty"`
}

type Address struct {
	Street string `json:"street,omitempty"`
	HouseNumber string `json:"house_number,omitempty"`
	PoBox string `json:"po_box,omitempty"`
	PostalCode string `json:"postal_code,omitempty"`
	City string `json:"city,omitempty"`
	Country string `json:"country,omitempty"`
	Province string `json:"province,omitempty"`
	Extra string `json:"extra,omitempty"`
	MailboxName string `json:"mailbox_name,omitempty"`
	IsUserAddressUpdated bool `json:"is_user_address_updated,omitempty"`
}

type RequestInquiryReference struct {
	Type string `json:"type,omitempty"`
	ID int `json:"id,omitempty"`
}

type Attachment struct {
	Description string `json:"description,omitempty"`
	ContentType string `json:"content_type,omitempty"`
	Urls []*AttachmentUrl `json:"urls,omitempty"`
}

type AttachmentUrl struct {
	Type string `json:"type,omitempty"`
	URL string `json:"url,omitempty"`
}

type PaymentArrivalExpected struct {
	Status string `json:"status,omitempty"`
	Time string `json:"time,omitempty"`
}

type AttachmentMonetaryAccountPayment struct {
	ID int `json:"id,omitempty"`
	MonetaryAccountID int `json:"monetary_account_id,omitempty"`
}

type Geolocation struct {
	Latitude string `json:"latitude,omitempty"`
	Longitude string `json:"longitude,omitempty"`
	Altitude string `json:"altitude,omitempty"`
	Radius string `json:"radius,omitempty"`
}

type Error struct {
	ErrorDescription string `json:"error_description,omitempty"`
	ErrorDescriptionTranslated string `json:"error_description_translated,omitempty"`
}

type PaymentFee struct {
	Value string `json:"value,omitempty"`
	Currency string `json:"currency,omitempty"`
	InvoiceID int `json:"invoice_id,omitempty"`
}

type BunqMeMerchantAvailable struct {
	MerchantType string `json:"merchant_type,omitempty"`
	Available bool `json:"available,omitempty"`
}

type BunqId struct {
	ID int `json:"id,omitempty"`
}

type CardBatchReplaceEntry struct{}

type CardPinAssignment struct {
	Type string `json:"type,omitempty"`
	MonetaryAccountID int `json:"monetary_account_id,omitempty"`
	Status string `json:"status,omitempty"`
	RoutingType string `json:"routing_type,omitempty"`
}

type CardBatchEntry struct{}

type CardCountryPermission struct {
	ID int `json:"id,omitempty"`
	Country string `json:"country,omitempty"`
}

type CardPrimaryAccountNumber struct {
	ID int `json:"id,omitempty"`
	UUID string `json:"uuid,omitempty"`
	Description string `json:"description,omitempty"`
	Status string `json:"status,omitempty"`
	MonetaryAccountID int `json:"monetary_account_id,omitempty"`
	FourDigit string `json:"four_digit,omitempty"`
	Type string `json:"type,omitempty"`
}

type Certificate struct {
	Certificate string `json:"certificate,omitempty"`
}

type Ubo struct {
	Name string `json:"name,omitempty"`
	DateOfBirth string `json:"date_of_birth,omitempty"`
	Nationality string `json:"nationality,omitempty"`
}

type NotificationFilter struct {
	NotificationDeliveryMethod string `json:"notification_delivery_method,omitempty"`
	NotificationTarget string `json:"notification_target,omitempty"`
	Category string `json:"category,omitempty"`
}

type TaxResident struct {
	ID int `json:"id,omitempty"`
	Country string `json:"country,omitempty"`
	TaxNumber string `json:"tax_number,omitempty"`
	Status string `json:"status,omitempty"`
}

type CompanyVatNumber struct {
	Type string `json:"type,omitempty"`
	Country string `json:"country,omitempty"`
	Value string `json:"value,omitempty"`
}

type CurrencyCloudBeneficiaryRequirementField struct {
	Label string `json:"label,omitempty"`
	Name string `json:"name,omitempty"`
	ValidationExpression string `json:"validation_expression,omitempty"`
	InputType string `json:"input_type,omitempty"`
}

type DraftPaymentResponse struct {
	Status string `json:"status,omitempty"`
	UserAliasCreated *LabelUser `json:"user_alias_created,omitempty"`
}

type DraftPaymentEntry struct {
	ID int `json:"id,omitempty"`
	Amount *Amount `json:"amount,omitempty"`
	Alias *MonetaryAccountReference `json:"alias,omitempty"`
	CounterpartyAlias *Pointer `json:"counterparty_alias,omitempty"`
	Description string `json:"description,omitempty"`
	MerchantReference string `json:"merchant_reference,omitempty"`
	Type string `json:"type,omitempty"`
	Attachment []*AttachmentMonetaryAccountPayment `json:"attachment,omitempty"`
}

type DraftPaymentAnchorObject struct {
	Payment string `json:"Payment,omitempty"`
	PaymentBatch string `json:"PaymentBatch,omitempty"`
}

type ScheduleAnchorObject struct {
	Payment string `json:"Payment,omitempty"`
	PaymentBatch string `json:"PaymentBatch,omitempty"`
}

type EventObject struct {
	BunqMeTab string `json:"BunqMeTab,omitempty"`
	BunqMeTabResultResponse string `json:"BunqMeTabResultResponse,omitempty"`
	BunqMeFundraiserResult string `json:"BunqMeFundraiserResult,omitempty"`
	Card string `json:"Card,omitempty"`
	CardDebit string `json:"CardDebit,omitempty"`
	DraftPayment string `json:"DraftPayment,omitempty"`
	FeatureAnnouncement string `json:"FeatureAnnouncement,omitempty"`
	IdealMerchantTransaction string `json:"IdealMerchantTransaction,omitempty"`
	Invoice string `json:"Invoice,omitempty"`
	ScheduledPayment string `json:"ScheduledPayment,omitempty"`
	ScheduledPaymentBatch string `json:"ScheduledPaymentBatch,omitempty"`
	ScheduledInstance string `json:"ScheduledInstance,omitempty"`
	MasterCardAction string `json:"MasterCardAction,omitempty"`
	BankSwitchServiceNetherlandsIncomingPayment string `json:"BankSwitchServiceNetherlandsIncomingPayment,omitempty"`
	Payment string `json:"Payment,omitempty"`
	PaymentBatch string `json:"PaymentBatch,omitempty"`
	RequestInquiryBatch string `json:"RequestInquiryBatch,omitempty"`
	RequestInquiry string `json:"RequestInquiry,omitempty"`
	RequestResponse string `json:"RequestResponse,omitempty"`
	ShareInviteBankInquiry string `json:"ShareInviteBankInquiry,omitempty"`
	ShareInviteBankResponse string `json:"ShareInviteBankResponse,omitempty"`
	SofortMerchantTransaction string `json:"SofortMerchantTransaction,omitempty"`
	TransferwisePayment string `json:"TransferwisePayment,omitempty"`
}

type SchedulePaymentEntry struct {
	Amount *Amount `json:"amount,omitempty"`
	Alias *MonetaryAccountReference `json:"alias,omitempty"`
	CounterpartyAlias *Pointer `json:"counterparty_alias,omitempty"`
	Description string `json:"description,omitempty"`
	Attachment []*BunqId `json:"attachment,omitempty"`
	MerchantReference string `json:"merchant_reference,omitempty"`
}

type ScheduleInstanceAnchorObject struct {
	Payment string `json:"Payment,omitempty"`
	PaymentBatch string `json:"PaymentBatch,omitempty"`
}

type LabelCard struct {
	UUID string `json:"uuid,omitempty"`
	Type string `json:"type,omitempty"`
	SecondLine string `json:"second_line,omitempty"`
	ExpiryDate string `json:"expiry_date,omitempty"`
	Status string `json:"status,omitempty"`
	LabelUser *LabelUser `json:"label_user,omitempty"`
}

type MasterCardActionReference struct {
	EventID int `json:"event_id,omitempty"`
}

type AdditionalInformation struct {
	Category string `json:"category,omitempty"`
	Reason string `json:"reason,omitempty"`
	Comment string `json:"comment,omitempty"`
	Attachment []*AttachmentMasterCardActionRefund `json:"attachment,omitempty"`
	TermsAndConditions string `json:"terms_and_conditions,omitempty"`
}

type AttachmentMasterCardActionRefund struct {
	ID int `json:"id,omitempty"`
}

type RequestReferenceSplitTheBillAnchorObject struct {
	BillingInvoice string `json:"BillingInvoice,omitempty"`
	DraftPayment string `json:"DraftPayment,omitempty"`
	MasterCardAction string `json:"MasterCardAction,omitempty"`
	Payment string `json:"Payment,omitempty"`
	PaymentBatch string `json:"PaymentBatch,omitempty"`
	RequestResponse string `json:"RequestResponse,omitempty"`
	ScheduleInstance string `json:"ScheduleInstance,omitempty"`
	WhitelistResult string `json:"WhitelistResult,omitempty"`
	TransferwisePayment string `json:"TransferwisePayment,omitempty"`
	CurrencyConversion string `json:"CurrencyConversion,omitempty"`
}

type WhitelistResultViewAnchoredObject struct {
	ID int `json:"id,omitempty"`
	RequestResponse string `json:"requestResponse,omitempty"`
	DraftPayment string `json:"draftPayment,omitempty"`
}

type ShareDetail struct {
	Payment *ShareDetailPayment `json:"payment,omitempty"`
	ReadOnly *ShareDetailReadOnly `json:"read_only,omitempty"`
	DraftPayment *ShareDetailDraftPayment `json:"draft_payment,omitempty"`
}

type ShareDetailPayment struct {
	MakePayments *bool `json:"make_payments,omitempty"`
	MakeDraftPayments *bool `json:"make_draft_payments,omitempty"`
	ViewBalance *bool `json:"view_balance,omitempty"`
	ViewOldEvents *bool `json:"view_old_events,omitempty"`
	ViewNewEvents *bool `json:"view_new_events,omitempty"`
}

type ShareDetailReadOnly struct {
	ViewBalance *bool `json:"view_balance,omitempty"`
	ViewOldEvents *bool `json:"view_old_events,omitempty"`
	ViewNewEvents *bool `json:"view_new_events,omitempty"`
}

type ShareDetailDraftPayment struct {
	MakeDraftPayments *bool `json:"make_draft_payments,omitempty"`
	ViewBalance *bool `json:"view_balance,omitempty"`
	ViewOldEvents *bool `json:"view_old_events,omitempty"`
	ViewNewEvents *bool `json:"view_new_events,omitempty"`
}

type MonetaryAccountProfileFill struct {
	Status string `json:"status,omitempty"`
	BalancePreferred *Amount `json:"balance_preferred,omitempty"`
	BalanceThresholdLow *Amount `json:"balance_threshold_low,omitempty"`
	Issuer *Issuer `json:"issuer,omitempty"`
}

type Issuer struct {
	Bic string `json:"bic,omitempty"`
	Name string `json:"name,omitempty"`
}

type MonetaryAccountProfileDrain struct {
	Status string `json:"status,omitempty"`
	BalancePreferred *Amount `json:"balance_preferred,omitempty"`
	BalanceThresholdHigh *Amount `json:"balance_threshold_high,omitempty"`
	SavingsAccountAlias *Pointer `json:"savings_account_alias,omitempty"`
}

type MonetaryAccountSetting struct {
	Color string `json:"color,omitempty"`
	Icon string `json:"icon,omitempty"`
	DefaultAvatarStatus string `json:"default_avatar_status,omitempty"`
	RestrictionChat string `json:"restriction_chat,omitempty"`
	SDDExpirationAction string `json:"sdd_expiration_action,omitempty"`
}

type CoOwner struct {
	Alias *Pointer `json:"alias,omitempty"`
	Status string `json:"status,omitempty"`
}

type BirdeeInvestmentPortfolioGoal struct {
	AmountTarget *Amount `json:"amount_target,omitempty"`
	TimeEnd string `json:"time_end,omitempty"`
}

type NotificationUrl struct {
	TargetURL string `json:"target_url,omitempty"`
	Category string `json:"category,omitempty"`
	EventType string `json:"event_type,omitempty"`
	Object any `json:"object,omitempty"`
}

type NotificationAnchorObject struct {
	BunqMeFundraiserResult string `json:"BunqMeFundraiserResult,omitempty"`
	BunqMeTab string `json:"BunqMeTab,omitempty"`
	BunqMeTabResultInquiry string `json:"BunqMeTabResultInquiry,omitempty"`
	BunqMeTabResultResponse string `json:"BunqMeTabResultResponse,omitempty"`
	ChatMessage string `json:"ChatMessage,omitempty"`
	DraftPayment string `json:"DraftPayment,omitempty"`
	IdealMerchantTransaction string `json:"IdealMerchantTransaction,omitempty"`
	Invoice string `json:"Invoice,omitempty"`
	MasterCardAction string `json:"MasterCardAction,omitempty"`
	MonetaryAccount string `json:"MonetaryAccount,omitempty"`
	Payment string `json:"Payment,omitempty"`
	PaymentBatch string `json:"PaymentBatch,omitempty"`
	RequestInquiry string `json:"RequestInquiry,omitempty"`
	RequestInquiryBatch string `json:"RequestInquiryBatch,omitempty"`
	RequestResponse string `json:"RequestResponse,omitempty"`
	ShareInviteBankInquiry string `json:"ShareInviteBankInquiry,omitempty"`
	ShareInviteBankResponse string `json:"ShareInviteBankResponse,omitempty"`
	ScheduledPayment string `json:"ScheduledPayment,omitempty"`
	ScheduledInstance string `json:"ScheduledInstance,omitempty"`
	User string `json:"User,omitempty"`
}

type UserApiKeyAnchoredUser struct {
	UserPerson string `json:"UserPerson,omitempty"`
	UserCompany string `json:"UserCompany,omitempty"`
	UserPaymentServiceProvider string `json:"UserPaymentServiceProvider,omitempty"`
}

type PermittedDevice struct {
	Description string `json:"description,omitempty"`
	IP string `json:"ip,omitempty"`
}

type TransferwiseRequirementField struct {
	Name string `json:"name,omitempty"`
	Group *TransferwiseRequirementFieldGroup `json:"group,omitempty"`
}

type TransferwiseRequirementFieldGroup struct {
	Key string `json:"key,omitempty"`
	Type string `json:"type,omitempty"`
	Name string `json:"name,omitempty"`
	RefreshRequirementsOnChange bool `json:"refresh_requirements_on_change,omitempty"`
	Required bool `json:"required,omitempty"`
	DisplayFormat string `json:"display_format,omitempty"`
	Example string `json:"example,omitempty"`
	MinLength string `json:"min_length,omitempty"`
	MaxLength string `json:"max_length,omitempty"`
	ValidationRegexp string `json:"validation_regexp,omitempty"`
	ValidationAsync *TransferwiseRequirementFieldGroupValidationAsync `json:"validation_async,omitempty"`
	ValuesAllowed *TransferwiseRequirementFieldGroupValuesAllowed `json:"values_allowed,omitempty"`
}

type TransferwiseRequirementFieldGroupValidationAsync struct {
	URL string `json:"url,omitempty"`
	Params *TransferwiseRequirementFieldGroupValidationAsyncParams `json:"params,omitempty"`
}

type TransferwiseRequirementFieldGroupValidationAsyncParams struct {
	Key string `json:"key,omitempty"`
	ParameterName string `json:"parameter_name,omitempty"`
	Required bool `json:"required,omitempty"`
}

type TransferwiseRequirementFieldGroupValuesAllowed struct {
	Key string `json:"key,omitempty"`
	Name string `json:"name,omitempty"`
}

type HealthCheckResult struct {
	Status string `json:"status,omitempty"`
	AllEntry []*HealthCheckResultEntry `json:"allEntry,omitempty"`
}

type HealthCheckResultEntry struct {
	Type string `json:"type,omitempty"`
	Status string `json:"status,omitempty"`
}

type MonetaryAccountReference struct{}

